### PR TITLE
Fix whitespace / indenting in README for code example

### PR DESCRIPTION
**Pull request by andygrunwald**

### CODE REVIEW

**Comment by elithrar** [comment]
The CI build is failing as pat relies on mux, and mux no longer builds on Go < 1.5. Opening a new issue.

**Comment by andygrunwald** [comment]
https://github.com/gorilla/pat/issues/17 for reference.

**Comment by elithrar** [comment]
@andygrunwald Can you rebase & re-push once #18 is merged?

**Comment by andygrunwald** [comment]
@elithrar Not needed anymore, because the changed happen already in https://github.com/gorilla/pat/commit/199c85a7f6d1ed2ecd6f071892d312c00d43b031

**Pull request closed without merging**
